name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project_dir:
          - 'ULP-frontend'
          - 'ULP-backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '${{ matrix.project_dir }}/package-lock.json'

      - name: Install dependencies
        working-directory: ${{ matrix.project_dir }}
        run: npm install

      - name: Build Project
        working-directory: ${{ matrix.project_dir }}
        run: npm run build
